routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::group([
        'namespace' => 'Web', 'as' => 'web.'
    ],function (){
        // Home Page
        Route::get('/', 'WebController@home')->name('home');
        Route::get('/quero-alugar', 'WebController@rent')->name('rent');
        Route::get('/quero-alugar/{slug}', 'WebController@rentProperty')->name('rentProperty');
        Route::get('/quero-comprar', 'WebController@buy')->name('buy');
        Route::get('/quero-comprar/{slug}', 'WebController@buyProperty')->name('buyProperty');
        Route::get('/filtro', 'WebController@filter')->name('filter');
        Route::get('/contato', 'WebController@contact')->name('contact');
    });

    Route::group(['prefix' => 'component','namespace' => 'Web', 'as' => 'component.'],function (){

        Route::post('main-filter/search','FilterController@search')->name('main-filter.search');
        Route::post('main-filter/category','FilterController@category')->name('main-filter.category');
        Route::post('main-filter/type','FilterController@type')->name('main-filter.type');
        Route::post('main-filter/neighborhood','FilterController@neighborhood')->name('main-filter.neighborhood');
        Route::post('main-filter/bedrooms','FilterController@bedrooms')->name('main-filter.bedrooms');
        Route::post('main-filter/suites','FilterController@suites')->name('main-filter.suites');
        Route::post('main-filter/bathrooms','FilterController@bathrooms')->name('main-filter.bathrooms');
        Route::post('main-filter/garage','FilterController@garage')->name('main-filter.garage');

    });

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

        /** Formulário de Login*/
        Route::get('/', 'AuthController@showLoginForm')->name('login');
        Route::post('/', 'AuthController@login')->name('login.do');

        /** Rotas Protegidas */
        Route::group(['middleware' => ['auth']],function (){
            //** Dashboard Home */
            Route::get('home', 'AuthController@home')->name('home');

            //** usuários */
            Route::get('users/team', 'UserController@team')->name('users.team');
            Route::resource('users','UserController');

            /** Empresas */
            Route::resource('companies','CompanyController');

            /** imóveis */
            Route::post('properties/image-get-cover','PropertyController@imageSetCover')->name('properties.imageSetCover');
            Route::delete('properties/image-remove','PropertyController@imageRemove')->name('properties.imageRemove');
            Route::resource('properties','PropertyController');

            /** Contratos */
            Route::post('contracts/get-data-owner','ContractController@getDataOwner')->name('contracts.getDataOwner');
            Route::post('contracts/get-data-acquirer','ContractController@getDataAcquirer')->name('contracts.getDataAcquirer');
            Route::post('contracts/get-data-property','ContractController@getDataProperty')->name('contracts.getDataProperty');
            Route::resource('contracts','ContractController');

        });


        /** Logout */
        Route::get('logout', 'AuthController@logout')->name('logout');

    });

app/Models/Company.php
<?php

    namespace App\Models;

    use Illuminate\Database\Eloquent\Factories\HasFactory;
    use Illuminate\Database\Eloquent\Model;

    class Company extends Model
    {
        use HasFactory;

        protected $fillable = [
            'sale',
            'rent',
            'user_id',
            'social_name',
            'alias_name',
            'document_company',
            'document_company_secondary',
            'zipcode',
            'street',
            'number',
            'complement',
            'neighborhood',
            'state',
            'city'
        ];

        public function owner()
        {
            return $this->hasOne(User::class,'id','user_id');
        }

        public function setDocumentCompanyAttribute($value)
        {
            $this->attributes['document_company'] = onlyNumber($value);
        }
        public function getDocumentCompanyAttribute($value)
        {
            return mask($value, '##.###.###/####-##');
        }

    }

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company as CompanyModel;
use http\Client\Curl\User;
use \App\Models\User as UserModel;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\CompanyRequest ;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = CompanyModel::all();

        return view('admin.companies.index',[
            'results' => $results
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $users = UserModel::orderBy('name')->get();
        return view('admin.companies.create', [
            'users' => $users,
            'selectedUser' => $request->user
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\Admin\CompanyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        $company =  CompanyModel::create($request->all());

        return redirect()->route('admin.companies.index', [
            'company' => $company->id
        ])->with([
            'color' => 'green',
            'message' => 'Registro salvo com sucesso.'
        ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = CompanyModel::where('id',$id)->first();
        $users = UserModel::orderBy('name')->get();

        return view('admin.companies.edit',[
            'item' => $item,
            'users' => $users
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Admin\CompanyRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, $id)
    {
        $company =  CompanyModel::where('id',$id)->first();
        $company->fill($request->all());
        $company->save();
        return redirect()->route('admin.companies.edit',$id)->with([
            'color' => 'green',
            'message' => 'Empresa atualizada com sucesso'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/companies/create.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-user-plus">Nova Empresa</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.users.index') }}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.companies.index') }}">Empresas</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.companies.create') }}" class="text-orange">Nova Empresa</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="dash_content_app_box">

            <div class="dash_content_app_box_stage">
                <form class="app_form" action="{{ route('admin.companies.store') }}" method="post">
                    @csrf
                    <label class="label"> <span class="legend">Usuário Responsável Legal:</span>
                        <select name="user_id" class="select2">
                            <option value="" selected>Selecione um responsável legal</option>
                            @foreach($users as $user)
                                <option value="{{ $user->id }}" {{ $user->id == $selectedUser ? 'selected': ''  }}>
                                    {{ $user->name }} ({{ $user->document }})
                                </option>
                            @endforeach
                        </select>


                    </label> <label class="label"> <span class="legend">*Razão Social:</span>
                        <input type="text" name="social_name" placeholder="Razão Social" value="{{ old('social_name') }}"/>
                    </label>

                    <label class="label"> <span class="legend">Nome Fantasia:</span>
                        <input type="text" name="alias_name" placeholder="Nome Fantasia" value="{{ old('alias_name') }}"/>
                    </label>

                    <div class="label_g2">
                        <label class="label"> <span class="legend">CNPJ:</span>
                            <input type="tel" name="document_company" class="mask-cnpj" placeholder="CNPJ da Empresa" value="{{ onlyNumber(old('document_company')) }}"/>
                        </label>

                        <label class="label"> <span class="legend">Inscrição Estadual:</span>
                            <input type="text" name="document_company_secondary" placeholder="Número da Inscrição" value="{{ old('document_company_secondary') }}"/>
                        </label>
                    </div>

                    <div class="app_collapse">
                        <div class="app_collapse_header mt-2 collapse">
                            <h3>Endereço</h3>
                            <span class="icon-minus-circle icon-notext"></span>
                        </div>

                        <div class="app_collapse_content">
                            <div class="label_g2">
                                <label class="label"> <span class="legend">*CEP:</span>
                                    <input type="tel" name="zipcode" class="mask-zipcode zip_code_search" placeholder="Digite o CEP" value="{{ old('zipcode') }}"/>
                                </label>
                            </div>

                            <label class="label"> <span class="legend">*Endereço:</span>
                                <input type="text" name="street" class="street" placeholder="Endereço Completo" value="{{ old('street') }}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label"> <span class="legend">*Número:</span>
                                    <input type="text" name="number" placeholder="Número do Endereço" value="{{ old('number') }}"/>
                                </label>

                                <label class="label"> <span class="legend">Complemento:</span>
                                    <input type="text" name="complement" placeholder="Completo (Opcional)" value="{{ old('complement') }}"/>
                                </label>
                            </div>

                            <label class="label"> <span class="legend">*Bairro:</span>
                                <input type="text" name="neighborhood" class="neighborhood" placeholder="Bairro" value="{{ old('neighborhood') }}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label"> <span class="legend">*Estado:</span>
                                    <input type="text" name="state" class="state" placeholder="Estado" value="{{ old('state') }}"/>
                                </label>

                                <label class="label"> <span class="legend">*Cidade:</span>
                                    <input type="text" name="city" class="city" placeholder="Cidade" value="{{ old('city') }}"/>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button class="btn btn-large btn-green icon-check-square-o" type="submit">Criar Empresa</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/companies/edit.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-user-plus">Edição de Empresa</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.users.index') }}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.companies.index') }}">Empresas</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.companies.create') }}" class="text-orange">Nova Empresa</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <form class="app_form" action="{{ route('admin.companies.update',$item->id) }}" method="post">
                    @csrf
                    @method('put')
                    <label class="label"> <span class="legend">Usuário Responsável Legal:</span>
                        <select name="user_id" class="select2">
                            @foreach($users as $user)
                                <option value="{{ $user->id }}" {{ $user->id === old('user_id') ? 'selected': ($user->id === $item->user_id ?'selected': '') }}>
                                    {{ $user->name }} ({{ $user->document }})
                                </option>
                            @endforeach

                        </select>
                        <p style="margin-top: 4px;">
                            <a href="{{ route('admin.users.edit', $item->user_id) }}" class="text-orange icon-link" style="font-size: .8em;" target="_blank">Acessar
                                Cadastro</a>
                        </p>
                    </label>

                    <label class="label"> <span class="legend">*Razão Social:</span>
                        <input type="text" name="social_name" placeholder="Razão Social" value="{{ old('social_name') ?? ($item->social_name?? '') }}"/>
                    </label>

                    <label class="label"> <span class="legend">Nome Fantasia:</span>
                        <input type="text" name="alias_name" placeholder="Nome Fantasia" value="{{ old('alias_name') ?? ($item->alias_name?? '') }}"/>
                    </label>

                    <div class="label_g2">
                        <label class="label"> <span class="legend">CNPJ:</span>
                            <input type="tel" name="document_company" class="mask-cnpj" placeholder="CNPJ da Empresa" value="{{ old('document_company') ?? ($item->document_company?? '') }}"/>
                        </label>

                        <label class="label"> <span class="legend">Inscrição Estadual:</span>
                            <input type="text" name="document_company_secondary" placeholder="Número da Inscrição" value="{{ old('document_company_secondary') ?? ($item->document_company_secondary?? '') }}"/>
                        </label>
                    </div>

                    <div class="app_collapse">
                        <div class="app_collapse_header mt-2 collapse">
                            <h3>Endereço</h3>
                            <span class="icon-minus-circle icon-notext"></span>
                        </div>

                        <div class="app_collapse_content">
                            <div class="label_g2">
                                <label class="label"> <span class="legend">*CEP:</span>
                                    <input type="tel" name="zipcode" class="mask-zipcode zip_code_search" placeholder="Digite o CEP" value="{{ old('zipcode') ?? ($item->zipcode?? '') }}"/>
                                </label>
                            </div>

                            <label class="label"> <span class="legend">*Endereço:</span>
                                <input type="text" name="street" class="street" placeholder="Endereço Completo" value="{{ old('street') ?? ($item->street?? '') }}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label"> <span class="legend">*Número:</span>
                                    <input type="text" name="number" placeholder="Número do Endereço" value="{{ old('number') ?? ($item->number?? '') }}"/>
                                </label>

                                <label class="label"> <span class="legend">Complemento:</span>
                                    <input type="text" name="complement" placeholder="Completo (Opcional)" value="{{ old('complement') ?? ($item->complement?? '') }}"/>
                                </label>
                            </div>

                            <label class="label"> <span class="legend">*Bairro:</span>
                                <input type="text" name="neighborhood" class="neighborhood" placeholder="Bairro" value="{{ old('neighborhood') ?? ($item->neighborhood?? '') }}"/>
                            </label>

                            <div class="label_g2">
                                <label class="label"> <span class="legend">*Estado:</span>
                                    <input type="text" name="state" class="state" placeholder="Estado" value="{{ old('state') ?? ($item->state?? '') }}"/>
                                </label>

                                <label class="label"> <span class="legend">*Cidade:</span>
                                    <input type="text" name="city" class="city" placeholder="Cidade" value="{{ old('city') ?? ($item->city?? '') }}"/>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="text-right">
                        <button class="btn btn-large btn-green icon-check-square-o" type="submit">Editar Empresar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/companies/filter.blade.php
<div class="dash_content_search">

    <div class="dash_content_search_close">
        <p class="text-right">
            <button class="btn btn-red icon-times icon-notext search_close"></button>
        </p>
    </div>

    <header>
        <h3 class="icon-search">Pesquisar por Empresa:</h3>
    </header>

    <main>
        <form action="">
            <label>
                <span>Nome:</span>
                <input type="text">
            </label>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <button class="btn btn-block btn-large btn-green icon-search">Filtrar</button>
        </form>
    </main>
</div>

resources/views/admin/companies/index.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-search">Filtro</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.users.index') }}">Clientes</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.companies.index') }}">Empresas</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="" class="text-orange">Filtro</a></li>
                    </ul>
                </nav>

                <a href="{{ route('admin.companies.create') }}" class="btn btn-orange icon-building-o ml-1">Criar Empresa</a>
                <button class="btn btn-green icon-search icon-notext ml-1 search_open"></button>
            </div>
        </header>

        @include('admin.companies.filter')

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <table id="dataTable" class="nowrap hover stripe" width="100" style="width: 100% !important;">
                    <thead>
                    <tr>
                        <th>Razão Social</th>
                        <th>Nome Fantasia</th>
                        <th>CNPJ</th>
                        <th>IE</th>
                        <th>Responsável</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($results as $result)
                        <tr>
                            <td>
                                <a href="{{ route('admin.companies.edit',$result->id) }}" class="text-orange">{{ $result->social_name }}</a>
                            </td>
                            <td>{{ $result->social_name }}</td>
                            <td>{{ $result->document_company }}</td>
                            <td>{{ $result->document_company_secondary }}</td>
                            <td>
                                <a href="{{ route('admin.users.edit',$result->user_id) }}" class="text-orange">{{ $result->owner->id }}</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </section>
@endsection