routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::group([
        'namespace' => 'Web', 'as' => 'web.'
    ],function (){
        // Home Page
        Route::get('/', 'WebController@home')->name('home');
        Route::get('/quero-alugar', 'WebController@rent')->name('rent');
        Route::get('/quero-alugar/{slug}', 'WebController@rentProperty')->name('rentProperty');
        Route::get('/quero-comprar', 'WebController@buy')->name('buy');
        Route::get('/quero-comprar/{slug}', 'WebController@buyProperty')->name('buyProperty');
        Route::get('/filtro', 'WebController@filter')->name('filter');
        Route::get('/contato', 'WebController@contact')->name('contact');
    });

    Route::group(['prefix' => 'component','namespace' => 'Web', 'as' => 'component.'],function (){

        Route::post('main-filter/search','FilterController@search')->name('main-filter.search');
        Route::post('main-filter/category','FilterController@category')->name('main-filter.category');
        Route::post('main-filter/type','FilterController@type')->name('main-filter.type');
        Route::post('main-filter/neighborhood','FilterController@neighborhood')->name('main-filter.neighborhood');
        Route::post('main-filter/bedrooms','FilterController@bedrooms')->name('main-filter.bedrooms');
        Route::post('main-filter/suites','FilterController@suites')->name('main-filter.suites');
        Route::post('main-filter/bathrooms','FilterController@bathrooms')->name('main-filter.bathrooms');
        Route::post('main-filter/garage','FilterController@garage')->name('main-filter.garage');

    });

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

        /** Formulário de Login*/
        Route::get('/', 'AuthController@showLoginForm')->name('login');
        Route::post('/', 'AuthController@login')->name('login.do');

        /** Rotas Protegidas */
        Route::group(['middleware' => ['auth']],function (){
            //** Dashboard Home */
            Route::get('home', 'AuthController@home')->name('home');

            //** usuários */
            Route::get('users/team', 'UserController@team')->name('users.team');
            Route::resource('users','UserController');

            /** Empresas */
            Route::resource('companies','CompanyController');

            /** imóveis */
            Route::post('properties/image-get-cover','PropertyController@imageSetCover')->name('properties.imageSetCover');
            Route::delete('properties/image-remove','PropertyController@imageRemove')->name('properties.imageRemove');
            Route::resource('properties','PropertyController');

            /** Contratos */
            Route::post('contracts/get-data-owner','ContractController@getDataOwner')->name('contracts.getDataOwner');
            Route::post('contracts/get-data-acquirer','ContractController@getDataAcquirer')->name('contracts.getDataAcquirer');
            Route::post('contracts/get-data-property','ContractController@getDataProperty')->name('contracts.getDataProperty');
            Route::resource('contracts','ContractController');

        });


        /** Logout */
        Route::get('logout', 'AuthController@logout')->name('logout');

    });

app/Models/Property.php
<?php

    namespace App\Models;

    use App\Support\Cropper;
    use Illuminate\Database\Eloquent\Factories\HasFactory;
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Support\Facades\Storage;
    use Illuminate\Support\Str;
    use phpDocumentor\Reflection\Types\Object_;

    class Property extends Model
    {
        use HasFactory;

        protected $fillable = [
            'sale',
            'rent',
            'category',
            'type',
            'user_id',
            'sale_price',
            'rent_price',
            'tribute',
            'condominium',
            'description',
            'bedrooms',
            'suites',
            'bathrooms',
            'rooms',
            'garage',
            'garage_covered',
            'area_total',
            'area_util',
            'zipcode',
            'street',
            'number',
            'complement',
            'neighborhood',
            'state',
            'city',
            'air_conditioning',
            'bar',
            'library',
            'barbecue_grill',
            'american_kitchen',
            'fitted_kitchen',
            'pantry',
            'edicule',
            'office',
            'bathtub',
            'fireplace',
            'lavatory',
            'furnished',
            'pool',
            'steam_room',
            'view_of_the_sea',
            'status',
            'title',
            'slug',
            'headline',
            'experience'
        ];

        public $list_category = [
            1 => 'Imóvel Residencial',
            2 => 'Comercial/Industrial',
            3 => 'Terreno'
        ];

        public $list_type = [
            'Imóvel Residencial' => [
                1 => 'Casa',
                2 => 'Cobertura',
                3 => 'Apartamento',
                4 => 'Studio',
                5 => 'Kitnet'
            ],
            'Comercial/Industrial' => [
                6 => 'Sala Comercial',
                7 => 'Depósito/Galpão',
                8 => 'Ponto Comercial'
            ],
            'Terreno' => [
                9 => 'Terreno'
            ]
        ];

        public function images()
        {
            return $this->hasMany(PropertiesImage::class, 'property_id', 'id')
                ->orderBy('cover', 'desc');
        }


        public function getDefaultCoverAttribute($value)
        {
            $image = $this->images()->where('cover', 1)->first();
            if(!!$image){
                $value = Storage::url(Cropper::thumb($image->path,1366,768)); ;
            } else {
                $value = url('backend/assets/images/realty.jpeg');
            }
            return $value;
        }

        public function getCoversAttribute()
        {
            $images = $this->images()->get();

            foreach ($images as $key => $image){
                 $covers[$key] = new \stdClass();
                 $covers[$key]->url = Storage::url(Cropper::thumb($image->path,1366,768));
                 $covers[$key]->cover = $image->cover;
            }
//            $value = url('backend/assets/images/realty.jpeg');
            return $covers;

        }

        public function getCoverAttribute($value)
        {
            if(isset($this->images()->get()[0]['path'])){
                $value = Storage::url(Cropper::thumb($this->images()->get()[0]['path'],1366,768)); ;
            }else {
                $value = 'backend/assets/images/realty.jpeg';
            }
            return $value;
        }

        public function scopeAvailable($query)
        {
            return $query->where('status', true);
        }

        public function scopeUnavailable($query)
        {
            return $query->where('status', false);
        }

        public function scopeRent($query)
        {
            return $query->where('rent', true);
        }

        public function scopeSale($query)
        {
            return $query->where('sale', true);
        }

        public function setSaleAttribute($value)
        {
            $this->attributes['sale'] = (!!$value) ? 1 : 0;
        }

        public function setRentAttribute($value)
        {
            $this->attributes['rent'] = (!!$value) ? 1 : 0;
        }

        public function setTypeAttribute($value)
        {
            $this->attributes['type'] =  $value;
        }
        public function getTypeAttribute($value)
        {
            return $value;
        }
        public function setCategoryAttribute($value)
        {
            $this->attributes['category'] =  $value;
        }
        public function setSalePriceAttribute($value)
        {
            $this->attributes['sale_price'] = fixDouble($value);
        }
        public function getSalePriceAttribute($value)
        {
            return fixDouble($value,'br');
        }
        public function setRentPriceAttribute($value)
        {
            $this->attributes['rent_price'] = fixDouble($value);
        }
        public function getRentPriceAttribute($value)
        {
            return fixDouble($value,'br');
        }
        public function setTributeAttribute($value)
        {
            $this->attributes['tribute'] = fixDouble($value);
        }
        public function getTributeAttribute($value)
        {
            return fixDouble($value,'br');
        }
        public function setCondominiumAttribute($value)
        {
            $this->attributes['condominium'] = fixDouble($value);
        }
        public function getCondominiumAttribute($value)
        {
            return fixDouble($value,'br');
        }
        public function setAirConditioningAttribute($value)
        {
            $this->attributes['air_conditioning'] = (!!$value) ? 1 : 0;
        }
        public function setBarAttribute($value)
        {
            $this->attributes['bar'] = (!!$value) ? 1 : 0;
        }
        public function setLibraryAttribute($value)
        {
            $this->attributes['library'] = (!!$value) ? 1 : 0;
        }
        public function setBarbecueGrillAttribute($value)
        {
            $this->attributes['barbecue_grill'] = (!!$value) ? 1 : 0;
        }
        public function setOfficeAttribute($value)
        {
            $this->attributes['office'] = (!!$value) ? 1 : 0;
        }
        public function setBathtubAttribute($value)
        {
            $this->attributes['bathtub'] = (!!$value) ? 1 : 0;
        }
        public function setFireplaceAttribute($value)
        {
            $this->attributes['fireplace'] = (!!$value) ? 1 : 0;
        }
        public function setLavatoryAttribute($value)
        {
            $this->attributes['lavatory'] = (!!$value) ? 1 : 0;
        }
        public function setFurnishedAttribute($value)
        {
            $this->attributes['furnished'] = (!!$value) ? 1 : 0;
        }
        public function setPoolAttribute($value)
        {
            $this->attributes['pool'] = (!!$value) ? 1 : 0;
        }
        public function setSteamRoomAttribute($value)
        {
            $this->attributes['steam_room'] = (!!$value) ? 1 : 0;
        }
        public function setViewOfTheSeaAttribute($value)
        {
            $this->attributes['view_of_the_sea'] = (!!$value) ? 1 : 0;
        }
        public function setAmericanKitchenAttribute($value)
        {
            $this->attributes['american_kitchen'] = (!!$value) ? 1 : 0;
        }
        public function setFittedKitchenAttribute($value)
        {
            $this->attributes['fitted_kitchen'] = (!!$value) ? 1 : 0;
        }
        public function setPantryAttribute($value)
        {
            $this->attributes['pantry'] = (!!$value) ? 1 : 0;
        }
        public function setEdiculeAttribute($value)
        {
            $this->attributes['edicule'] = (!!$value) ? 1 : 0;
        }

        public function setStatusAttribute($value)
        {
            $this->attributes['status'] = !!$value;
        }

        public function getStatusAttribute($value)
        {
            return !!$value;
        }

        public function setSlug()
        {
            if (!!$this->title) {
                $this->attributes['slug'] = Str::slug($this->title) . '-' . $this->id;
                $this->save();
            }
        }

        public function getTypeTextAttribute($value){
            foreach ($this->list_type as $types){
                foreach ($types as $key => $type) {
                    if ($this->type == $key) {
                        return $type;
                    }
                }
            }
            return  '';
        }
    }

resources/views/admin/properties/filter.blade.php
<div class="dash_content_search">

    <div class="dash_content_search_close">
        <p class="text-right">
            <button class="btn btn-red icon-times icon-notext search_close"></button>
        </p>
    </div>

    <header>
        <h3 class="icon-search">Pesquisar por Imóveis:</h3>
    </header>

    <main>
        <form action="">
            <label>
                <span>Nome:</span>
                <input type="text">
            </label>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <div class="label_double">
                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>

                <label class="label_50">
                    <span>Documento:</span>
                    <input type="text" size="2">
                </label>
            </div>

            <label>
                <span>Documento:</span>
                <input type="text">
            </label>

            <button class="btn btn-block btn-large btn-green icon-search">Filtrar</button>
        </form>
    </main>
</div>

resources/views/admin/properties/index.blade.php
@extends('admin.layout.master')
@section('content')
    <section class="dash_content_app">

        <header class="dash_content_app_header">
            <h2 class="icon-search">Filtro</h2>

            <div class="dash_content_app_header_actions">
                <nav class="dash_content_app_breadcrumb">
                    <ul>
                        <li><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                        <li><a href="{{ route('admin.properties.index') }}">Imóveis</a></li>
                        <li class="separator icon-angle-right icon-notext"></li>
                    </ul>
                </nav>

                <a href="{{ route('admin.properties.create') }}" class="btn btn-orange icon-home ml-1">Criar Imóvel</a>
                <button class="btn btn-green icon-search icon-notext ml-1 search_open"></button>
            </div>
        </header>

        @include('admin.properties.filter')

        <div class="dash_content_app_box">
            <div class="dash_content_app_box_stage">
                <div class="realty_list">
                    @if (!!count($properties))
                        @foreach($properties as $item)

                            <div class="realty_list_item mb-1">
                                <div class="realty_list_item_actions_stats">
                                    <img src="{{ $item->default_cover }}" alt="">
                                    <ul>
                                        @if (!!$item->sale && !!$item->sale_price)
                                            <li>Venda: R$ {{ $item->sale_price }}</li>
                                        @endif
                                        @if (!!$item->rent && !!$item->rent_price)
                                            <li>Aluguel: R$ {{$item->rent_price }}</li>
                                        @endif

                                    </ul>
                                </div>
                                <div class="realty_list_item_content">
                                    <h4>{{ $list_category[$item->category] }} - {{ $list_type_simple[$item->type] }}</h4>

                                    <div class="realty_list_item_card">
                                        <div class="realty_list_item_card_image">
                                            <span class="icon-realty-location"></span>
                                        </div>
                                        <div class="realty_list_item_card_content">
                                            <span class="realty_list_item_description_title">Bairro:</span>
                                            <span class="realty_list_item_description_content">{{ $item->neighborhood }}</span>
                                        </div>
                                    </div>

                                    <div class="realty_list_item_card">
                                        <div class="realty_list_item_card_image">
                                            <span class="icon-realty-util-area"></span>
                                        </div>
                                        <div class="realty_list_item_card_content">
                                            <span class="realty_list_item_description_title">Área Útil:</span>
                                            <span class="realty_list_item_description_content">{{ $item->area_util }}m&sup2;</span>
                                        </div>
                                    </div>

                                    <div class="realty_list_item_card">
                                        <div class="realty_list_item_card_image">
                                            <span class="icon-realty-bed"></span>
                                        </div>
                                        <div class="realty_list_item_card_content">
                                            <span class="realty_list_item_description_title">Domitórios:</span>
                                            <span class="realty_list_item_description_content">{{ $item->bedrooms + $item->suites }} Quartos<br>
                                                                    @if (!!$item->suites)
                                                    <span>Sendo {{ $item->suites }} suítes</span></span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="realty_list_item_card">
                                        <div class="realty_list_item_card_image">
                                            <span class="icon-realty-garage"></span>
                                        </div>
                                        <div class="realty_list_item_card_content">
                                            <span class="realty_list_item_description_title">Garagem:</span>
                                            <span class="realty_list_item_description_content">{{ $item->garage }} Vagas<br>
                                                                    @if(!!$item->garage_covered)
                                                    <span>Sendo {{ $item->garage_covered }} cobertas</span>
                                                @endif
                                                                </span>
                                        </div>
                                    </div>

                                </div>

                                <div class="realty_list_item_actions">
                                    <ul>
                                        <li class="icon-eye">1234 Visualizações</li>
                                    </ul>
                                    <div>
                                        <a href="{{ route('admin.properties.show',['property'=> $item->id]) }}" class="btn btn-blue icon-eye">Visualizar Imóvel</a>
                                        <a href="{{ route('admin.properties.edit',['property'=> $item->id]) }}" class="btn btn-green icon-pencil-square-o">Editar Imóvel</a>
                                    </div>
                                </div>
                            </div>

                        @endforeach
                    @else
                        <div class="no-content">Não foram encontrados registros!</div>
                    @endif
                </div>
            </div>
        </div>
    </section>
@endsection