routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::group([
        'namespace' => 'Web', 'as' => 'web.'
    ],function (){
        // Home Page
        Route::get('/', 'WebController@home')->name('home');
        Route::get('/quero-alugar', 'WebController@rent')->name('rent');
        Route::get('/quero-alugar/{slug}', 'WebController@rentProperty')->name('rentProperty');
        Route::get('/quero-comprar', 'WebController@buy')->name('buy');
        Route::get('/quero-comprar/{slug}', 'WebController@buyProperty')->name('buyProperty');
        Route::get('/filtro', 'WebController@filter')->name('filter');
        Route::get('/contato', 'WebController@contact')->name('contact');
    });

    Route::group(['prefix' => 'component','namespace' => 'Web', 'as' => 'component.'],function (){

        Route::post('main-filter/search','FilterController@search')->name('main-filter.search');
        Route::post('main-filter/category','FilterController@category')->name('main-filter.category');
        Route::post('main-filter/type','FilterController@type')->name('main-filter.type');
        Route::post('main-filter/neighborhood','FilterController@neighborhood')->name('main-filter.neighborhood');
        Route::post('main-filter/bedrooms','FilterController@bedrooms')->name('main-filter.bedrooms');
        Route::post('main-filter/suites','FilterController@suites')->name('main-filter.suites');
        Route::post('main-filter/bathrooms','FilterController@bathrooms')->name('main-filter.bathrooms');
        Route::post('main-filter/garage','FilterController@garage')->name('main-filter.garage');

    });

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

        /** Formulário de Login*/
        Route::get('/', 'AuthController@showLoginForm')->name('login');
        Route::post('/', 'AuthController@login')->name('login.do');

        /** Rotas Protegidas */
        Route::group(['middleware' => ['auth']],function (){
            //** Dashboard Home */
            Route::get('home', 'AuthController@home')->name('home');

            //** usuários */
            Route::get('users/team', 'UserController@team')->name('users.team');
            Route::resource('users','UserController');

            /** Empresas */
            Route::resource('companies','CompanyController');

            /** imóveis */
            Route::post('properties/image-get-cover','PropertyController@imageSetCover')->name('properties.imageSetCover');
            Route::delete('properties/image-remove','PropertyController@imageRemove')->name('properties.imageRemove');
            Route::resource('properties','PropertyController');

            /** Contratos */
            Route::post('contracts/get-data-owner','ContractController@getDataOwner')->name('contracts.getDataOwner');
            Route::post('contracts/get-data-acquirer','ContractController@getDataAcquirer')->name('contracts.getDataAcquirer');
            Route::post('contracts/get-data-property','ContractController@getDataProperty')->name('contracts.getDataProperty');
            Route::resource('contracts','ContractController');

        });


        /** Logout */
        Route::get('logout', 'AuthController@logout')->name('logout');

    });

resources/views/admin/layout/master.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0">

    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/reset.css')) }}"/>
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/libs.css')) }}"/>
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/boot.css')) }}"/>
    <link rel="stylesheet" href="{{ url(mix('backend/assets/css/style.css')) }}"/>
    <link rel="icon" type="image/png" href="{{ url(mix('backend/assets/images/favicon.png')) }}"/>

    @hasSection('css_block')
        @yield('css_block')
    @endif
    <meta name="csrf-token" content="{{ csrf_token() }}"/>

    <title>Admin - Site Control</title>
</head>
<body>

<div class="ajax_load">
    <div class="ajax_load_box">
        <div class="ajax_load_box_circle"></div>
        <p class="ajax_load_box_title">Aguarde, carregando...</p>
    </div>
</div>

<div class="ajax_response"></div>

@php
    $userName = \Illuminate\Support\Facades\Auth::user()->name;
    if (\Illuminate\Support\Facades\File::exists(public_path('/storage/'.\Illuminate\Support\Facades\Auth::user()->cover))) {
        $cover = '/storage/'.\Illuminate\Support\Facades\Auth::user()->cover;
    } else {
        $cover = '/backend/assets/images/avatar.jpg';
    }
@endphp

<div class="dash">
    <aside class="dash_sidebar">
        <article class="dash_sidebar_user">
            <img class="dash_sidebar_user_thumb" src="{{ url($cover) }}" alt="" title=""/>

            <h1 class="dash_sidebar_user_name">
                <a href="">{{ $userName }}</a>
            </h1>
        </article>

        <ul class="dash_sidebar_nav">
            <li class="dash_sidebar_nav_item {{ isActive('admin.home') }}">
                <a class="icon-tachometer" href="{{ route('admin.home') }}">Dashboard</a>
            </li>
            <li class="dash_sidebar_nav_item {{ isActive('admin.users') }}{{ isActive('admin.companies') }}">
                <a class="icon-users" href="{{ route('admin.users.index') }}">Clientes</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class="{{ isActive('admin.users.index') }}"><a href="{{ route('admin.users.index') }}">Ver Todos</a></li>
                    <li class="{{ isActive('admin.companies.index') }}"><a href="{{ route('admin.companies.index') }}">Empresas</a></li>
                    <li class="{{ isActive('admin.users.team') }}"><a href="{{ route('admin.users.team') }}">Time</a></li>
                    <li class="{{ isActive('admin.users.create') }}"><a href="{{ route('admin.users.create') }}">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item {{ isActive('admin.properties') }}" >
                <a class="icon-home" href="{{ route('admin.properties.index') }}">Imóveis</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class="{{ isActive('admin.properties.index') }}"><a href="{{ route('admin.properties.index') }}">Ver Todos</a></li>
                    <li class="{{ isActive('admin.properties.create') }}"><a href="{{ route('admin.properties.create') }}">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item {{ isActive('admin.contracts') }}" >
                <a class="icon-file-text" href="{{ route('admin.contracts.index') }}">Contratos</a>
                <ul class="dash_sidebar_nav_submenu">
                    <li class="{{ isActive('admin.contracts.index') }}"><a href="{{ route('admin.contracts.index') }}">Ver Todos</a></li>
                    <li class="{{ isActive('admin.contracts.create') }}"><a href="{{ route('admin.contracts.create') }}">Criar Novo</a></li>
                </ul>
            </li>
            <li class="dash_sidebar_nav_item"><a class="icon-reply" href="">Ver Site</a></li>
            <li class="dash_sidebar_nav_item"><a class="icon-sign-out on_mobile" href="{{ route('admin.logout') }}" target="_blank">Sair</a></li>
        </ul>

    </aside>

    <section class="dash_content">

        <div class="dash_userbar">
            <div class="dash_userbar_box">
                <div class="dash_userbar_box_content">
                    <span class="icon-align-justify icon-notext mobile_menu transition btn btn-green"></span>
                    <h1 class="transition">
                        <i class="icon-imob text-orange"></i><a href="">Up<b>Admin</b></a>
                    </h1>
                    <div class="dash_userbar_box_bar no_mobile">
                        <a class="text-red icon-sign-out" href="{{ route('admin.logout') }}">Sair</a>
                    </div>
                </div>
            </div>
        </div>

        @if ($errors->any())
            @foreach($errors->all() as $message)
                <x-messages-error type="error" :message="$message" class="mt-4"/>
            @endforeach
        @endif

        @if (session()->exists('message'))
            <x-flash-message :message="session()->get('message')" class="mt-4"></x-flash-message>
        @endif

        <div class="dash_content_box">
{{--            @include('flash-message')--}}
            @yield('content')
        </div>
    </section>
</div>

<script src="{{ asset('assets/js/jquery.min.js') }}"></script>
<script src="{{ url(mix('backend/assets/js/tinymce/tinymce.min.js')) }}"></script>
<script src="{{ url(mix('backend/assets/js/libs.js')) }}"></script>
<script src="{{ url(mix('backend/assets/js/scripts.js')) }}"></script>

@hasSection('js_block')
    @yield('js_block')
@endif
</body>
</html>